[phases.setup]
  nixPkgs = ['...', 'jq'] # jq is needed to parse the outputPath from our angular.json file

[phases.install]
[start]
  cmd = "npm i --legacy-peer-deps"

[phases.build]
cmd = "npm run build"

[start]
  cmd = "npm run start"